name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: cd1
      run: cd ..
    - name: cd2
      run: cd ..
    
    - name: make
      run: make all

    
   
    
